service: hello-world-api
frameworkVersion: '2 || 3'

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /sayHello
          method: get
